const routes = { '/': 'Home', '/about': 'About', '/experience': 'Experience', '/skills': 'Skills', '/protosem': 'Protosem', '/contact': 'Contact' };
let content, editorOpen = false, activeEditorPage = 'Home';
const app = document.querySelector('#app');
const esc = (s = '') => String(s).replace(/[&<>'"]/g, c => ({ '&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;' }[c]));
const list = (items = []) => items.map(x => `<li>${esc(x)}</li>`).join('');
const tags = (items = []) => `<div class="tag-row">${items.map(x => `<span class="tag">${esc(x)}</span>`).join('')}</div>`;
const media = (url, label = 'Replaceable image') => url ? `<div class="media"><img src="${esc(url)}" alt="${esc(label)}" /></div>` : `<div class="media"><span class="placeholder-label">${esc(label)} — edit source</span></div>`;
const link = (href, label, primary = false, external = false) => `<a class="button ${primary ? 'primary':''}" href="${esc(href || '#')}" ${external ? 'target="_blank" rel="noreferrer"':''}>${esc(label)} <span>↗</span></a>`;
function nav(current) { return `<header class="topbar shell"><a class="brand" href="/">MITRA<span>.</span></a><nav class="nav">${Object.entries(routes).map(([path, name]) => `<a href="${path}" class="${name === current ? 'active':''}">${name}</a>`).join('')}</nav></header>`; }
function footer() { return `<footer class="footer shell"><span>DESIGNED AND DEVELOPED BY MITRA B</span><span>ENGINEERING PORTFOLIO · ${new Date().getFullYear()}</span></footer>`; }
function home(){ const d=content; const photo = d.identity && d.identity.photo ? d.identity.photo : ''; const resumeHref = (d.identity && d.identity.resume && d.identity.resume !== '#') ? d.identity.resume : '/resume.html'; return `<main class="page shell"><section class="hero"><div><div class="eyebrow">Mechanical systems · robotics · product thinking</div><h1>${esc(d.identity.name)}<br><span style="color:#729dff">${esc(d.identity.title)}</span></h1><div class="role-line" id="role">${esc(d.roles[0])}</div><p class="lead">${esc(d.identity.tagline)}</p><div class="button-row">${link(resumeHref,'Resume',true,false)}${link(d.identity.linkedin,'LinkedIn',false,true)}<a href="/contact" class="button">Contact <span>→</span></a></div></div><div class="portrait">${photo ? `<img src="${esc(photo)}" alt="Portrait of ${esc(d.identity.name)}">` : ''}<span class="placeholder-label">Professional photo — replace in editor</span></div></section><section class="stats">${d.stats.map(s=>`<div class="stat"><strong>${esc(s.value)}</strong><span>${esc(s.label)}</span></div>`).join('')}</section></main>`; }
function about(){const d=content.about;return `<main class="page shell"><div class="split"><section class="section-head"><div class="eyebrow">01 / About</div><h1>${esc(d.headline)}</h1><p class="lead">${esc(d.copy)}</p></section><section><div class="eyebrow">Engineering journey</div><div class="timeline" style="margin-top:33px">${d.journey.map(x=>`<article class="time-item"><span class="time-date">${esc(x.date)}</span><h3>${esc(x.title)}</h3><p>${esc(x.description)}</p></article>`).join('')}</div></section></div></main>`;}
function experience(){const e=content.experience;const r=e.racing;return `<main class="page shell"><section class="section-head"><div class="eyebrow">02 / Experience</div><h1>Work built around evidence.</h1><p class="lead">Engineering case studies that surface the reasoning, process and proof behind the work.</p></section><section class="case"><div class="case-grid">${media(r.banner,'E ZEALL Racing — hero banner')}<div class="case-body"><div class="eyebrow">${esc(r.eyebrow)}</div><h2>${esc(r.name)}</h2><p class="muted">${esc(r.summary)}</p>${tags(r.skills)}<div class="detail-grid"><div class="detail"><b>Challenge</b><p>${esc(r.challenge)}</p></div><div class="detail"><b>Decision</b><p>${esc(r.decision)}</p></div><div class="detail"><b>Result</b><p>${esc(r.result)}</p></div><div class="detail"><b>Lesson</b><p>${esc(r.lesson)}</p></div></div></div></div><div class="case-body"><div class="eyebrow">Responsibilities</div><ul class="muted">${list(r.responsibilities)}</ul><div class="grid3">${r.gallery.map(x=>media(x.url,x.label)).join('')}</div></div></section><section style="margin-top:80px"><div class="eyebrow">Industrial internships</div><h2>Where engineering meets operation.</h2><div class="grid3">${e.internships.map(i=>`<article class="intern"><div class="logo">${esc(i.company.split(' ').map(x=>x[0]).join('').slice(0,3))}</div><p class="time-date">${esc(i.period)}</p><h3>${esc(i.company)}</h3><p class="muted">${esc(i.summary)}</p>${tags(i.technologies)}<div class="detail"><b>Learning</b><p>${esc(i.learning)}</p></div></article>`).join('')}</div></section><section style="margin-top:80px" class="case"><div class="case-grid"><div class="case-body"><div class="eyebrow">Research</div><h2>${esc(e.research.title)}</h2><p class="muted">${esc(e.research.abstract)}</p><p class="time-date">${esc(e.research.status)}</p>${tags(e.research.technologies)}<div style="margin-top:20px">${link(e.research.paper,'Download paper')}</div></div>${media(e.research.image,'Research image')}</div></section><section style="margin-top:80px"><div class="eyebrow">Engineering projects</div><h2>Systems in development.</h2><div class="project-grid">${content.projects.map(projectCard).join('')}</div></section></main>`;}
function projectCard(p){return `<article class="project-card">${media(p.banner,p.title+' banner')}<div class="case-body"><p class="time-date">${esc(p.type)}</p><h3>${esc(p.title)}</h3><p class="muted">${esc(p.solution)}</p>${tags(p.skills)}<div class="button-row" style="margin-top:18px">${link(p.github,'GitHub',false,true)}</div></div></article>`;}
function skills(){return `<main class="page shell"><section class="section-head"><div class="eyebrow">03 / Skills</div><h1>Tools are only valuable when they ship better decisions.</h1><p class="lead">A working record of software, analysis and systems practices — without abstract ratings or progress bars.</p></section><section class="skill-list">${content.skills.map(s=>`<article class="skill"><div class="skill-logo">${esc(s.logo)}</div><div class="skill-content"><div class="eyebrow">${esc(s.category)}</div><h2 style="font-size:32px">${esc(s.name)}</h2><p class="muted">${esc(s.description)}</p><p class="time-date">WHERE USED</p><p class="muted" style="font-size:13px">${esc(s.where)}</p>${tags(s.tags)}<p class="muted" style="font-size:12px;margin-top:14px">Engineering note — ${esc(s.notes)}</p></div>${media(s.image,s.name+' project evidence')}</article>`).join('')}</section></main>`;}
function protosem(){const weeks=content.protosem;return `<main class="page shell"><section class="section-head"><div class="eyebrow">04 / Protosem</div><h1>Learning, documented as engineering work.</h1><p class="lead">A living weekly dashboard for objectives, evidence, feedback and next actions.</p></section><div class="dash-tools"><input id="week-search" placeholder="Search work, skills, challenges…"><select id="week-filter"><option value="">All weeks</option>${weeks.map(w=>`<option value="${esc(w.week)}">Week ${esc(w.week)}</option>`).join('')}</select></div><section id="week-list">${weeks.map(week).join('')}</section></main>`;}
function week(w){return `<article class="week" data-week="${esc(w.week)}" data-search="${esc(Object.values(w).flat().join(' ')).toLowerCase()}"><div class="week-num">${esc(w.week)}</div><div><div class="week-main"><div><h4>Objectives</h4><p>${esc(w.objectives)}</p></div><div><h4>Work completed</h4><p>${esc(w.work)}</p></div><div><h4>Challenge → solution</h4><p>${esc(w.challenge)} → ${esc(w.solution)}</p></div><div><h4>Reflection / next</h4><p>${esc(w.reflection)} ${esc(w.next)}</p></div></div><div style="margin-top:17px">${tags(w.skills)}<p class="time-date" style="margin-top:12px">${esc(w.hours)} hours · Mentor: ${esc(w.mentor)}</p></div></div></article>`;}
function contact(){const d=content.identity,c=content.contact;return `<main class="page shell"><section class="contact-grid"><div>${d.photo?`<div class="portrait"><img src="${esc(d.photo)}" alt="${esc(d.name)}"></div>`:media('', 'Professional photo — replace in editor')}</div><div><div class="eyebrow">05 / Contact</div><h1>${esc(c.heading)}</h1><p class="lead">${esc(c.message)}</p><div class="contact-list"><a href="mailto:${esc(d.email)}"><b>Email</b>${esc(d.email)}</a><a href="tel:${esc(d.phone)}"><b>Phone</b>${esc(d.phone)}</a><div><b>Location</b>${esc(d.location)}</div><a href="${esc(d.linkedin)}" target="_blank" rel="noreferrer"><b>LinkedIn</b>Connect professionally ↗</a><a href="${esc(d.resume)}" target="_blank"><b>Resume</b>Download document ↗</a></div></div></section><section style="max-width:780px;margin:85px auto 0"><div class="eyebrow">Send a message</div><h2>Start the conversation.</h2><form class="form" id="contact-form"><input required placeholder="Your name" aria-label="Your name"><input required type="email" placeholder="Your email" aria-label="Your email"><textarea required placeholder="What are you working on?" aria-label="Message"></textarea><button class="button primary" type="submit">Send enquiry →</button></form></section></main>`;}
function editor(){ if(!editorOpen)return ''; let section = activeEditorPage === 'Home' ? content : activeEditorPage === 'About' ? content.about : activeEditorPage === 'Experience' ? { experience:content.experience, projects:content.projects } : activeEditorPage === 'Skills' ? content.skills : activeEditorPage === 'Protosem' ? content.protosem : { identity:content.identity, contact:content.contact};return `<aside class="editor"><div class="editor-top"><div><div class="eyebrow">Live content editor</div><h3>Edit ${activeEditorPage}</h3><p>Change any text, list, image URL or project data.</p></div><button class="button" data-close>Close</button></div><textarea id="json-editor" spellcheck="false">${esc(JSON.stringify(section,null,2))}</textarea><div class="upload-note">Click inside an image field such as <code>"photo": ""</code>, then choose a file. Its path is inserted automatically.</div><div class="editor-actions"><label class="button" for="image-upload">Upload image</label><input id="image-upload" type="file" accept="image/jpeg,image/png,image/webp,image/gif,image/svg+xml" hidden><button class="button primary" data-save>Save locally</button><button class="button" data-export>Export backup</button><span class="save-state" id="save-state"></span></div></aside>`;}
function render(){const path=routes[location.pathname] ? location.pathname : '/';if(path!==location.pathname)history.replaceState({},'',path);const page=routes[path];const views={Home:home,About:about,Experience:experience,Skills:skills,Protosem:protosem,Contact:contact};app.innerHTML=nav(page)+views[page]()+footer()+editor();document.title=`${page === 'Home' ? content.identity.name : page+' · '+content.identity.name} — Engineering Portfolio`; bind();if(content && content.identity){app.querySelectorAll('img').forEach(img=>{if(img.getAttribute('alt')==='Portrait of '+content.identity.name){img.src=content.identity.photo || img.src;}});}}
async function refreshContentAndRender(){
  try {
    const loaded = await loadContent();
    if (loaded) content = loaded;
  } catch (e) {
    console.error(e);
  }
  render();
}
function bind(){const close=document.querySelector('[data-close]');if(close)close.onclick=()=>{editorOpen=false;render()};const save=document.querySelector('[data-save]');if(save)save.onclick=saveEditor;const upload=document.querySelector('#image-upload');if(upload)upload.onchange=uploadImage;const exportBtn=document.querySelector('[data-export]');if(exportBtn)exportBtn.onclick=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(content,null,2)],{type:'application/json'}));a.download='site-content-backup.json';a.click();URL.revokeObjectURL(a.href)};const search=document.querySelector('#week-search'),filter=document.querySelector('#week-filter');if(search)search.oninput=filterWeeks;if(filter)filter.onchange=filterWeeks;const form=document.querySelector('#contact-form');if(form)form.onsubmit=e=>{e.preventDefault();toast('Thanks — connect the form to your preferred email service in the next setup step.')};}
function filterWeeks(){const q=document.querySelector('#week-search').value.toLowerCase(), f=document.querySelector('#week-filter').value;document.querySelectorAll('.week').forEach(x=>x.hidden=!(x.dataset.search.includes(q)&&(!f||x.dataset.week===f)))}
function insertUploadedUrl(area, url, field='photo'){const text=area.value;const escapedUrl=JSON.stringify(url);const pattern=new RegExp(`"${field}"\\s*:\\s*"(?:[^"\\\\]|\\\\.)*"`);const match=pattern.exec(text);if(match){const replacement=`"${field}": ${escapedUrl}`;const start=text.indexOf(match[0]);area.value=text.slice(0,start)+replacement+text.slice(start+match[0].length);const cursor=start + replacement.length;area.selectionStart=area.selectionEnd=cursor;return true;}const cursor=typeof area.selectionStart==='number' ? area.selectionStart : text.length;const before=text.slice(0,cursor);const after=text.slice(cursor);const quoteStart=before.lastIndexOf('"');const quoteEnd=after.indexOf('"');if(quoteStart>=0&&quoteEnd>=0){area.value=text.slice(0,quoteStart+1)+url+text.slice(quoteStart+1+quoteEnd);area.selectionStart=area.selectionEnd=quoteStart+1+url.length;return true;}area.value=`${text.slice(0,cursor)}"${url}"${text.slice(cursor)}`;area.selectionStart=area.selectionEnd=cursor+1+url.length;return true;}
function getEditorSectionData(){const area=document.querySelector('#json-editor');const fallback=activeEditorPage==='Home'?content:activeEditorPage==='About'?content.about:activeEditorPage==='Experience'?{experience:content.experience,projects:content.projects}:activeEditorPage==='Skills'?content.skills:activeEditorPage==='Protosem'?content.protosem:{identity:content.identity,contact:content.contact};try{return JSON.parse(area.value)}catch(err){area.value=JSON.stringify(fallback,null,2);toast('The JSON editor had invalid syntax, so the last valid content was restored.');return fallback;}}
async function saveEditor(){const state=document.querySelector('#save-state');try{const value=getEditorSectionData();if(activeEditorPage==='Home'){content=value;}else if(activeEditorPage==='About')content.about=value;else if(activeEditorPage==='Experience'){content.experience=value.experience;content.projects=value.projects}else if(activeEditorPage==='Skills')content.skills=value;else if(activeEditorPage==='Protosem')content.protosem=value;else{content.identity=value.identity;content.contact=value.contact}try{localStorage.setItem('mitra_portfolio_content',JSON.stringify(content));}catch(err){}state.textContent='Saved locally!';setTimeout(()=>{editorOpen=false;render();toast('Content saved locally in browser. Click "Export backup" to download updated JSON file.');},500)}catch(e){state.textContent='Error: '+e.message}}
async function uploadImage(event){const file=event.target.files[0],state=document.querySelector('#save-state'),area=document.querySelector('#json-editor');if(!file)return;try{if(file.size>5*1024*1024)throw new Error('Please choose an image smaller than 5 MB.');state.textContent='Reading image…';const dataUrl=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=()=>reject(new Error('Could not read image.'));reader.readAsDataURL(file)});let field='photo';if(activeEditorPage==='Experience')field='banner';else if(activeEditorPage==='Skills')field='image';else if(activeEditorPage==='About')field='image';insertUploadedUrl(area, dataUrl, field);state.textContent='Image inserted — saving…';await saveEditor();event.target.value=''}catch(e){state.textContent='Error: '+e.message}}
function toast(text){const n=document.createElement('div');n.className='notice';n.textContent=text;document.body.append(n);setTimeout(()=>n.remove(),3200)}
document.addEventListener('click',e=>{const a=e.target.closest('a[href]');if(a&&a.origin===location.origin&&routes[a.pathname]){e.preventDefault();history.pushState({},'',a.pathname);refreshContentAndRender()}});window.addEventListener('popstate',refreshContentAndRender);
async function loadContent(){
  try {
    const saved = localStorage.getItem('mitra_portfolio_content');
    if (saved) return JSON.parse(saved);
  } catch(e){}
  try {
    const r = await fetch('/site-content.json');
    if (!r.ok) throw new Error('Static content unavailable');
    return await r.json();
  } catch (e) {
    return {};
  }
}
loadContent().then(d=>{content=d;render()}).catch(e=>{app.innerHTML=`<main class="page shell"><h1>Content unavailable</h1><p class="lead">Could not load portfolio content.</p></main>`;console.error(e)});
