const tasks = [
  {
    number:'01', title:'HTTP LED Web Control', subtitle:'Local Wi-Fi · HTTP REST · GPIO · Day 1', intro:'Connect an ESP32 to local Wi-Fi and run a lightweight web server. Browser requests to /api/on and /api/off control the onboard LED in real time.', objectives:['Understand HTTP and basic REST API design','Build a browser interface for an embedded device','Control a GPIO digital output','Apply polling and embedded UI principles'], code:`#include <WiFi.h>\n#include <WebServer.h>\n\nconst char* ssid = "YOUR_WIFI_SSID";\nconst char* password = "YOUR_WIFI_PASSWORD";\nWebServer server(80);\nconst int ledPin = 2;\n\nvoid handleOn() { digitalWrite(ledPin, HIGH); server.send(200, "text/plain", "ON"); }\nvoid handleOff() { digitalWrite(ledPin, LOW); server.send(200, "text/plain", "OFF"); }\n\nvoid setup() {\n  Serial.begin(115200); pinMode(ledPin, OUTPUT);\n  WiFi.begin(ssid, password);\n  while (WiFi.status() != WL_CONNECTED) delay(500);\n  server.on("/api/on", handleOn); server.on("/api/off", handleOff);\n  server.begin();\n}\nvoid loop() { server.handleClient(); }`, photos:[]
  },
  {
    number:'02', title:'MQTT Cloud Dashboard with Relay Control', subtitle:'Adafruit IO · MQTT Pub/Sub · 230V Relay · Day 2', intro:'Move from local HTTP to cloud publish–subscribe control. Adafruit IO receives the command and publishes it through MQTT to an ESP32, which switches a relay.', objectives:['Control a device from anywhere through the cloud','Understand MQTT publishers, subscribers and brokers','Log control events in a dashboard','Design a scalable IoT control pattern'], code:`#include <AdafruitIO_WiFi.h>\n#define WIFI_SSID "YOUR_WIFI_SSID"\n#define WIFI_PASS "YOUR_WIFI_PASSWORD"\n#define IO_USERNAME "YOUR_ADAFRUIT_IO_USERNAME"\n#define IO_KEY "YOUR_ADAFRUIT_IO_KEY"\nAdafruitIO_WiFi io(IO_USERNAME, IO_KEY, WIFI_SSID, WIFI_PASS);\nAdafruitIO_Feed *esp = io.feed("esp");\n#define RELAY_PIN 26\nvoid handleESPMessage(AdafruitIO_Data *data) {\n  String command = data->toString(); command.trim(); command.toUpperCase();\n  if (command == "ON") digitalWrite(RELAY_PIN, HIGH);\n  if (command == "OFF") digitalWrite(RELAY_PIN, LOW);\n}\nvoid setup() { pinMode(RELAY_PIN, OUTPUT); esp->onMessage(handleESPMessage); io.connect(); }\nvoid loop() { io.run(); }`, photos:[]
  },
  {
    number:'03', title:'Google Assistant Voice Control via IFTTT', subtitle:'IFTTT · Webhooks · Voice API · Day 3', intro:'Add a voice-control layer to Task 2. Google Assistant recognises a trigger phrase, IFTTT sends a Webhook to Adafruit IO, and MQTT delivers the command to the existing ESP32 firmware.', objectives:['Connect voice intent recognition to an IoT workflow','Use IFTTT Webhooks to trigger cloud actions','Document an end-to-end voice-to-GPIO architecture'], architecture:'Voice input → Google Assistant → IFTTT applet → Adafruit IO API → MQTT → ESP32 → Relay → Bulb', code:'Trigger phrase: “Hey Google, activate bulb on”\nWebhook action: POST ON/OFF to the Adafruit IO feed\nESP32 action: parse MQTT value and set relay GPIO', photos:[]
  },
  {
    number:'04', title:'Forge — Full-Stack Smart Home', subtitle:'ESP32 · Firebase · Web Dashboard · Intermediate', intro:'Combine hardware sensing, cloud synchronisation and a web dashboard into one production-style smart-home system.', objectives:['Stream DHT11 and LDR readings to Firebase','Synchronise relay state in real time','Support manual and automatic modes','Build a dashboard for monitoring and export'], subsections:[['04.1 — Hardware','ESP32 Environmental Monitoring & Relay Control','DHT11 + LDR readings are sampled every two seconds, the light value is smoothed, and an active-LOW relay controls the load.'],['04.2 — Cloud','Firebase Cloud Backend & Real-Time Sync','Firebase Realtime Database stores sensor history, relay state, operating mode and the LDR threshold.'],['04.3 — Dashboard','Web Dashboard & User Interface','The JavaScript dashboard displays temperature and humidity, toggles the bulb, changes modes, updates the threshold and exports sensor data as CSV.']], code:`// Core Firebase data paths\n/appliances/bulbState\n/settings/mode\n/settings/ldrThreshold\n/sensorData\n\n// Dashboard actions\nset(ref(db, 'appliances/bulbState'), true);\nset(ref(db, 'settings/mode'), 'automatic');`, photos:[]
  }
];

const esc = s => String(s ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const photoSlots = (task) => `<div class="photo-box">${[0,1,2,3].map((_, i) => `<div class="photo-slot" data-task="${task.number}" data-photo="${i}"><span>Photo ${i+1}</span><button type="button" data-photo-button>+ Add photo URL</button></div>`).join('')}</div>`;
const renderTask = task => `<article class="iot-card"><div class="eyebrow">Task ${task.number}</div><h2>${esc(task.title)}</h2><div class="time-date">${esc(task.subtitle)}</div><p>${esc(task.intro)}</p><details><summary>View full task details</summary><h3>Learning objectives</h3><ul>${task.objectives.map(x => `<li>${esc(x)}</li>`).join('')}</ul>${task.architecture ? `<h3>System architecture</h3><p>${esc(task.architecture)}</p>` : ''}${(task.subsections || []).map(x => `<h3>${esc(x[0])} — ${esc(x[1])}</h3><p>${esc(x[2])}</p>`).join('')}<h3>Implementation notes</h3><pre class="iot-code">${esc(task.code)}</pre></details><h3>Task photos</h3>${photoSlots(task)}</article>`;
document.querySelector('#iot-tasks').innerHTML = tasks.map(renderTask).join('');
document.addEventListener('click', e => { const button=e.target.closest('[data-photo-button]'); if(!button) return; const slot=button.closest('.photo-slot'); const url=prompt('Paste an image URL for this task:'); if(!url) return; slot.innerHTML=`<img src="${esc(url)}" alt="Task ${esc(slot.dataset.task)} photo ${esc(slot.dataset.photo)}"><button type="button" data-photo-button>Change photo</button>`; });
